# Generated by Django 2.2.16 on 2021-07-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancellation',
            field=models.IntegerField(db_column='cancellation', default=1, verbose_name='用户逻辑删除'),
        ),
    ]
